FROM openjdk:latest
MAINTAINER "Rizwan <797979>"
COPY target/03-User-Management-Portal-App.jar  /usr/app/
WORKDIR /usr/app/
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "03-User-Management-Portal-App.jar"]